AWSTemplateFormatVersion: '2010-09-09'
Description: CloudTrail Audit Lambda with SNS alerting and EventBridge schedule

Parameters:
  WhitelistedRegions:
    Type: CommaDelimitedList
    Description: List of whitelisted regions
  HoursBack:
    Type: Number
    Default: 6
    Description: How many hours back to scan CloudTrail logs
  NotificationEmail:
    Type: String
    Description: Email address to receive alerts
  ScheduleRateMinutes:
    Type: Number
    Default: 60
    Description: Frequency to run audit (in minutes)
  CodeS3Bucket:
    Type: String
  CodeS3Key:
    Type: String
  LayerS3Bucket:
    Type: String
  LayerS3Key:
    Type: String

Resources:

  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: LambdaFunctionErrors
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref CloudTrailAuditLambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  
  GeoRequestsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: requests-layer
      Description: Python requests module
      Content:
        S3Bucket: !Ref LayerS3Bucket
        S3Key: !Ref LayerS3Key
      CompatibleRuntimes:
        - python3.13

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CloudTrailAlertTopic

  AlertTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref NotificationEmail
      Protocol: email
      TopicArn: !Ref AlertTopic

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudtrail-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudTrailAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudtrail:LookupEvents
                  - ec2:DescribeRegions
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref AlertTopic

  CloudTrailAuditLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloudtrail-audit-lambda
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Timeout: 900
      MemorySize: 512
      Layers:
        - !Ref GeoRequestsLayer
      Environment:
        Variables:
          WHITELISTED_REGIONS: !Join [",", !Ref WhitelistedRegions]
          HOURS_BACK: !Ref HoursBack
          ALERT_TOPIC_ARN: !Ref AlertTopic

  AuditScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: CloudTrailAuditSchedule
      ScheduleExpression: !Sub rate(${ScheduleRateMinutes} minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt CloudTrailAuditLambda.Arn
          Id: CloudTrailAuditLambdaTarget
      
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CloudTrailAuditLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt AuditScheduleRule.Arn

Outputs:
  LambdaFunction:
    Value: !Ref CloudTrailAuditLambda
  LambdaRole:
    Value: !Ref LambdaExecutionRole
  AlertTopicArn:
    Value: !Ref AlertTopic

